### ISSUE TITLE
.JAR files successfully uploaded but

### ISSUE THREAD

**Issue by kuranjpr** [Esri/activemq-for-geoevent#4] opened 2018-04-25 02:29 UTC
.JAR files successfully uploaded but not able to see Active MQ Inbound and outbound Connector in the components of the ArcGIS Geoevent manager.

**Comment by kuranjpr** [comment] 2018-04-25 02:31
Could you please help on getting inbound and outbound connector in the components?

**Comment by mzesri** [comment] 2018-04-25 22:58
I was unable to reproduce this with our development version 10.6.1.  I would imagine it should work with previous versions as well.  GeoEvent does have problem loading large jar files.  But if the jar file is uploaded successfully, it should be available for connectors and inputs.

Here is what I did:

1. clone this repo.  
2. run mvn clean install WITHOUT making any changes.
3. start GeoEevent.  Used "add local transport" button to add this jar.
4. Verified that the inbund/outbound transports do show up and their versions are 10.4.1.
5. Created a connector with the inbound amqp transport
6. Went to create input with this new connector.  All transport properties showed up.

What version of GeoEvent are you using?  Which step didn't go as expected.

**Comment by kuranjpr** [comment] 2018-04-30 17:06
Hello Ming,
I was able to add local Active MQ transport in 10.5.1 and create the connector and input.  I did all the necessary changes with the TCP port. How do i know that the TCP port is sending the messages to the Geo event manager in Input in Monitor tab correctly.
Here is the screen shot
![activemq-text-in](https://user-images.githubusercontent.com/12579530/39440006-83377c34-4c77-11e8-8a53-6032aafc6003.jpg)

**Comment by kuranjpr** [comment] 2018-04-30 17:09
Hello Ming,
I was able to add local Active MQ transport in 10.5.1 and create the
connector and input. I did all the necessary changes with the TCP port. How
do i know that the TCP port is sending the messages to the Geo event
manager in Input in Monitor tab correctly.
Here is the screen shot




With Best Regards,


Prashant R. Kuranjekar, GISP

Senior Technologist - Geospatial

Cellno: +1-813-528-2801

**Comment by mzesri** [comment] 2018-05-07 22:43
I am not familiar with this particular transport.  But generally speaking, the input count on the monitor page indicates how many events this input has received.  If you think it should be receiving events but the count is still 0, you may need to take a look at the karaf.log file or the log tab on the manager page.  If no error is showing up in the logs, I will suspect whether you are connected to the right message queue.  You can also try debug through your transport code.  I believe the GeoEvent Develop Guide that comes with the install talks about how to debug a custom component.

**Comment by brudo** [comment] 2019-01-04 22:39
I also had issues with the transport failing to deploy consistently on 10.6.0, which could be similar to what the original poster described. I made changes included in PR #5 to fix it. The version in Esri:master did work on 10.5.1. However, I did not re-test the original version with 10.6.1 when it came out.

**Comment by hanoch** [comment] 2019-01-04 23:36
@brudo I left some comments on PR #5

**Comment by brudo** [comment] 2019-09-15 04:20
@hanoch I think it is safe to say this issue can now closed as not repeatable since PR #5 was merged (thank you), and current master targets 10.6.1 specifically (but works with 10.7.x in my experience). Any comment from original poster @kuranjpr on how the current master works on 10.6.x and 10.7.x?

**Closed as completed** 2019-09-15 18:37 UTC
